<?php
/**
 * Fuel is a fast, lightweight, community driven PHP 5.4+ framework.
 *
 * @package    Fuel
 * @version    1.8.2
 * @author     Fuel Development Team
 * @license    MIT License
 * @copyright  2010 - 2019 Fuel Development Team
 * @link       https://fuelphp.com
 */

return array(
	/**
	 * -------------------------------------------------------------------------
	 *  The base URL of the application
	 * -------------------------------------------------------------------------
	 *
	 *  You can set this to a full or relative URL:
	 *
	 *      'base_url' => '/foo/',
	 *      'base_url' => 'http://foo.com/'
	 *
	 *  It MUST contain a trailing slash (/).
	 *
	 *  Set this to null to have it automatically detected.
	 *
	 */

	// 'base_url' => null,

	/**
	 * -------------------------------------------------------------------------
	 *  Any suffix that needs to be added to
	 * -------------------------------------------------------------------------
	 *
	 *  URL's generated by Fuel. If the suffix is an extension, make sure to
	 *  include the dot.
	 *
	 *      'url_suffix' => '.html',
	 *
	 *  Set this to an empty string if no suffix is used.
	 *
	 */

	// 'url_suffix' => '',

	/**
	 * -------------------------------------------------------------------------
	 *  The name of the main bootstrap file
	 * -------------------------------------------------------------------------
	 *
	 *  Set this to 'index.php if you don't use URL rewriting.
	 *
	 */

	// 'index_file' => false,

	// 'profiling' => false,

	/**
	 * -------------------------------------------------------------------------
	 *  Default location for the file cache
	 * -------------------------------------------------------------------------
	 */

	// 'cache_dir' => APPPATH.'cache/',

	/**
	 * -------------------------------------------------------------------------
	 *  Settings for the file finder cache
	 *
	 *  Note: The Cache class has it's own config!
	 * -------------------------------------------------------------------------
	 *
	 *  The 'cache_lifetime' value is in seconds.
	 *
	 */

	// 'caching' => false,

	// 'cache_lifetime' => 3600,

	/**
	 * -------------------------------------------------------------------------
	 *  Callback to use with ob_start(), set this to 'ob_gzhandler'
	 *  for gzip encoding of output
	 * -------------------------------------------------------------------------
	 */

	// 'ob_callback' => null,

	// 'errors' => array(
		/**
		 * ---------------------------------------------------------------------
		 *  Which errors should we show, but continue execution? You can add
		 *  the following:
		 *
		 *      E_NOTICE, E_WARNING, E_DEPRECATED, E_STRICT
		 *
		 *  to mimic PHP's default behaviour (which is to continue
		 *  on non-fatal errors). We consider this bad practice.
		 * ---------------------------------------------------------------------
		 */

		// 'continue_on' => array(),

		/**
		 * ---------------------------------------------------------------------
		 *  How many errors should we show before we stop showing them?
		 *
		 *  Note: This is useful to prevents out-of-memory errors.
		 * ---------------------------------------------------------------------
		 */

		// 'throttle' => 10,

		/**
		 * ---------------------------------------------------------------------
		 *  Should notices from Error::notice() be shown?
		 * ---------------------------------------------------------------------
		 */

		// 'notices' => true,

		/**
		 * ---------------------------------------------------------------------
		 *  Render previous contents or show it as HTML?
		 * ---------------------------------------------------------------------
		 */

		// 'render_prior' => false,
	// ),

	/**
	 * -------------------------------------------------------------------------
	 *  Localization & internationalization settings
	 * -------------------------------------------------------------------------
	 */

	/**
	 *  The default language.
	 */

	// 'language' => 'en',

	/**
	 *  Fallback language when file isn't available for default language.
	 */

	// 'language_fallback' => 'en',

	/**
	 *  PHP set_locale() setting. Use null to not set.
	 */

	// 'locale' => 'en_US',

	/**
	 * -------------------------------------------------------------------------
	 *  Internal string encoding charset
	 * -------------------------------------------------------------------------
	 */

	// 'encoding' => 'UTF-8',

	/**
	 * -------------------------------------------------------------------------
	 *  DateTime settings
	 * -------------------------------------------------------------------------
	 */

	/**
	 *  The server offset in seconds from GMT timestamp when time() is used.
	 */

	// 'server_gmt_offset' => 0,

	/**
	 *  Change the server's default timezone. This is optional.
	 */

	// 'default_timezone' => null,

	/**
	 * -------------------------------------------------------------------------
	 *  Logging threshold.
	 * -------------------------------------------------------------------------
	 *
	 *  Can be set to any of the following:
	 *
	 *      Fuel::L_NONE
	 *      Fuel::L_ERROR
	 *      Fuel::L_WARNING
	 *      Fuel::L_DEBUG
	 *      Fuel::L_INFO
	 *      Fuel::L_ALL
	 *
	 */

	// 'log_threshold'   => Fuel::L_WARNING,
	// 'log_path'        => APPPATH.'logs/',
	// 'log_date_format' => 'Y-m-d H:i:s',

	/**
	 * -------------------------------------------------------------------------
	 *  Security settings
	 * -------------------------------------------------------------------------
	 */

	'security' => array(
		

		'uri_filter' => array('htmlentities'),

	

		'output_filter' => array('Security::htmlentities'),

	

		'whitelisted_classes' => array(
			'Fuel\\Core\\Presenter',
			'Fuel\\Core\\Response',
			'Fuel\\Core\\View',
			'Fuel\\Core\\ViewModel',
			'Closure',
		),
	),



	'package_paths' => array(
		PKGPATH,
	),


	
);
